name: ml-env  # 环境名称
channels:
  - defaults
  - conda-forge  # conda-forge 提供更多最新包
dependencies:
  - python=3.8  # 使用 Python 3.8
  - pip  # 安装 pip
  - cudatoolkit=11.3  # 安装 CUDA 11.3（如果你需要手动指定 CUDA）
  - pip  # 安装 pip 后，指定安装 torch 和 cuda
  - scikit-learn  # 常用机器学习库
  - pandas  # 数据分析
  - numpy  # 数值计算
  - matplotlib  # 绘图库
  - seaborn  # 可视化库
  - jupyterlab  # Jupyter 交互式计算
  - ipykernel  # Jupyter 内核
  - tqdm  # 进度条库
  - flask  # Web 框架
  - transformers=4.11.3  # HuggingFace Transformers，用于 NLP
  - pip:
      - torch==1.10.2+cu113  # 使用 pip 安装 PyTorch 1.10.2 + CUDA 11.3
      - torchvision==0.11.3+cu113  # 计算机视觉相关
      - deepseek  # 你的深度学习库
      - --extra-index-url=https://download.pytorch.org/whl/cu113  ##