name: my_deep_learning_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.2.0
  - matplotlib=3.6.2
  - seaborn=0.11.2
  - scikit-image=0.19.3
  - opencv=4.6.0
  - jupyterlab=3.5.0
  - pip
  - pip:
      - torch==2.0.0+cu121  # 安装 PyTorch 2.x 并指定 CUDA 12.1
      - torchvision==0.15.0+cu121  # 适配的 torchvision 版本
      - torchaudio==2.0.0  # 适配的 torchaudio 版本
      - transformers==4.30.0
      - vllm==0.1.0
      - torchmetrics
      - datasets
      - accelerate
      - tensorboard
      - pytorch-lightning
      - mlflow
      - plotly
      - jupyter
      - seaborn
      - tqdm
